<?php

namespace AppBundle\Repository;

/**
 * ejemploRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ejemploRepository extends \Doctrine\ORM\EntityRepository
{
}
